# Generated by Django 4.2.8 on 2023-12-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish_content', '0002_post_updated_at_alter_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time',
            field=models.DateField(auto_now=True),
        ),
    ]
