# Generated by Django 4.2.8 on 2023-12-14 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish_content', '0004_post_head_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file_upload',
            field=models.FileField(blank=True, upload_to='wish_content/files/%Y/%m/%d/'),
        ),
    ]
